[build]
  command = "npm ci && npm run build"
  publish = ".next"
  environment = { NODE_VERSION = "20" }

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.processing]
  skip_processing = true

# Force longer timeout
[build.environment]
  NPM_FLAGS = "--max-timeout=1200000"
